# Generated by Django 4.1.3 on 2023-01-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0004_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200, null=True)),
                ('consultation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosp.consultation')),
            ],
        ),
    ]
