# Generated by Django 4.1.3 on 2023-01-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the appointment', verbose_name='Day of the appointment')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('state', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Canceled', max_length=20, null=True)),
                ('specialty', models.CharField(choices=[('General practice', 'General practice'), ('Clinical radiology', 'Clinical radiology'), ('Anaesthesia', 'Anaesthesia'), ('Ophthalmology', 'Ophthalmology')], max_length=200, null=True)),
                ('consulted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hosp.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=200)),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosp.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosp.doctor')),
            ],
        ),
    ]
