# Generated by Django 4.1.3 on 2023-01-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_appointment_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_state', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=10)),
                ('consultation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosp.consultation')),
            ],
        ),
    ]
